cmake-format test

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,23 +1,30 @@
 #
-# pre-commit: auto linting
+# pre-commit: auto formatting
 #
 
 # color define
 RED="\e[0;31m"
 END="\e[0m"
 
-# find clang-format
+# ---- cmake-format ----
+CMAKE_FORMAT=`which cmake-format`
+if [ "${CMAKE_FORMAT}" = "" ]
+then
+	echo -n "${RED} Can't find cmake-format ${END}.\n"
+	exit 1
+fi
+find . \( -name '*.cmake' -o -name 'CMakeLists.txt' \) -exec cmake-format -i {} \;
+
+# ---- clang-format ----
 CLANG_FORMAT=`which clang-format`
 if [ "$CLANG_FORMAT" = "" ]
 then
 	echo -n "${RED} Can't find clang-format ${END}.\n"
 	exit 1
 fi
-
-# linting
 CXX_FILES_FILTER="\.([chi](pp|xx)|(cc|hh|ii)|[CHI])$"
-CXX_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "$CXX_FILES_FILTER")
-if [ "$CXX_CHANGED_FILES" != "" ]
+CXX_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "${CXX_FILES_FILTER}")
+if [ "${CXX_CHANGED_FILES}" != "" ]
 then
 	$CLANG_FORMAT -i -style=file ${CXX_CHANGED_FILES}
 fi
